Styling
ankitt26/Bookstore pull request #5
Opened 2023-06-22 16:56 UTC by ankitt26

2023-06-22 18:07 UTC, Ghiftee requested changes
## STATUS: CHANGES REQUIRED ♻️♻️
Hello @ankitt26 👋🏽 

Good job working on the project so far! 
To highlight 👍🏽 
✔️ App matches design layout
✔️ App runs smoothly
✔️ No linter errors

However, there are some issues that you need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/107632780/229314554-3700de13-2c00-46d5-bc77-46ad09af7467.gif)

## Required Changes ♻️
_Check the comments under the review 👇🏽 _

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-06-22 18:07 UTC, Ghiftee commented on src/App.css
> +  /* font-family: 'Ysabeau', sans-serif; */
- [x] Please do not leave commented code in your codebase for a cleaner finish

2023-06-22 18:07 UTC, Ghiftee commented on src/CSS/Book.module.css
> +  /* background-color: rgb(152, 203, 31); */
- [x] Please do not leave non-descriptive commented code in your codebase for a cleaner finish

2023-06-22 18:07 UTC, Ghiftee commented on src/CSS/Book.module.css
> +  /* padding-right: 20px; */
- [x] Please do not leave non-descriptive commented code in your codebase for a cleaner finish

2023-06-22 18:07 UTC, Ghiftee commented on src/CSS/Circularbar.module.css
> +  /* background-color: aquamarine; */
- [x] Please do not leave non-descriptive commented code in your codebase for a cleaner finish

2023-06-22 18:07 UTC, Ghiftee commented on src/CSS/Navbar.module.css
> +} */
- [x] Please do not leave non-descriptive commented code in your codebase for a cleaner finish

2023-06-22 18:07 UTC, Ghiftee commented on src/CSS/Navbar.module.css
> +  /* margin: 1.125rem 2.563rem 0.688rem 0; */
- [x] Please do not leave non-descriptive commented code in your codebase for a cleaner finish

2023-06-22 18:07 UTC, Ghiftee commented on src/CSS/Navbar.module.css
> +  /* margin: 1.125rem 41.5rem 0.688rem 2.563rem; */
- [x] Please do not leave non-descriptive commented code in your codebase for a cleaner finish

2023-06-22 18:07 UTC, Ghiftee commented on src/CSS/Book.module.css
> +  background: #fff !important;
- [x] I suggest you do not use `!important` here as it can be considered bad practice. Instead of using the important selector, you can consider looking into the [specificity](https://www.smashingmagazine.com/2010/04/css-specificity-and-inheritance/) of the elements as that is why CSS is called `cascading`. In this case though, I do not think you need to use `!important` as your app works fine without it.

2023-06-22 18:07 UTC, Ghiftee commented on src/CSS/Navbar.module.css
> +  color: #2c2b2b;
- [x] It is very important as developers that we follow the given design so kindly make changes to the numbered section in the image below. For numbers `1 and 2`, please capitalize them and make them the same colour as in the [zeplin design](https://app.zeplin.io/project/5b35a9e13227086040f8eb75/screen/5b695e29bb8c844f118f9378), and for number `3`, please include the rounded border on the icon.

### Zeplin design
![Screenshot 2023-06-22 at 18 26 59 (2)](https://github.com/ankitt26/Bookstore/assets/64774936/aef40ff3-8761-4a8e-800f-adfb32f69a77)

### Your design
![Screenshot 2023-06-22 at 18 27 18 (2)](https://github.com/ankitt26/Bookstore/assets/64774936/558c4ca3-a44e-4db4-9bd2-bd7931351a0c)

2023-06-22 18:07 UTC, Ghiftee commented on src/CSS/Book.module.css
> +}
- [ ] Great job styling these sections, however, kindly make the following changes to make your design look like the given design. 
- `Item 1` has the wrong colour and font-family
- `Item 2` has the wrong font-family
- `Item 3` has the wrong colour
- `Item 4` has the wrong colour
- `Item 5` has the wrong colour and font-family
- Kindly make the text in `Item 6` uppercase

### Given design
![Screenshot 2023-06-22 at 18 47 10 (2)](https://github.com/ankitt26/Bookstore/assets/64774936/4d292337-2bf1-4f1f-8af7-75db1799ca19)

### Your design
![Screenshot 2023-06-22 at 18 47 05 (2)](https://github.com/ankitt26/Bookstore/assets/64774936/59a8b366-98c9-480a-a681-4fc745f61da9)

2023-06-23 08:12 UTC, AdnanOlarmmi requested changes
Hi @ankitt26, 

This is Adnan Is-haq, your beloved code reviewer,

You've done a very good job so far, but a few things still need to be worked on before moving on to the next project, but you're so close!

![You're Almost there, funny one eyed alien](https://user-images.githubusercontent.com/41163571/217957948-6d8d9f33-125c-4724-954f-330eed60533c.gif)

## Highlights
- Nice UI design.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-23 08:12 UTC, AdnanOlarmmi commented on src/CSS/Book.module.css
> +  font-family: RobotoSlab, sans-serif;
> * [ ]  Great job styling these sections, however, kindly make the following changes to make your design look like the given design.
> * `Item 1` has the wrong colour and font-family
> * `Item 2` has the wrong font-family
> * `Item 3` has the wrong colour
> * `Item 4` has the wrong colour
> * `Item 5` has the wrong colour and font-family
> * Kindly make the text in `Item 6` uppercase
> 
> ### Given design
> ![Screenshot 2023-06-22 at 18 47 10 (2)](https://user-images.githubusercontent.com/64774936/248015824-4d292337-2bf1-4f1f-8af7-75db1799ca19.png)
> 
> ### Your design
> ![Screenshot 2023-06-22 at 18 47 05 (2)](https://user-images.githubusercontent.com/64774936/248015881-59a8b366-98c9-480a-a681-4fc745f61da9.png)

- [x] For the above review comment, the font family didn't change accordingly because it wasn't added correctly, 
it should be written as `font-family: "Roboto Slab", san-serif;`

The roboto slab word has space in between and it's in Capital case just like that.

2023-06-23 08:12 UTC, AdnanOlarmmi commented on src/CSS/Book.module.css
> +  background: #fff !important;
-[ ] Just like the previous reviewer said, kindly remove the `!important` keyword, since the code works without it, and specificity should be considered for future purposes.

2023-06-23 08:27 UTC, ankitt26 commented on src/CSS/Book.module.css
> +  font-family: RobotoSlab, sans-serif;
@AdnanOlarmmi Thank you so much, I didn't know how to write the Roboto Slab font family. Thanks for the detailed explanation 👌.

2023-06-23 09:06 UTC, Felix45 approved these changes
# Approved :green_circle: 
Hi @ankitt26, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://camo.githubusercontent.com/5f6b955314ad7a8c010bb5de56877a2fa40a6d2bc5aeabd629e6a150f73afd97/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f744965434c6b423867655974572f67697068792e676966" width="350px" />

## Highlights :heavy_check_mark: 
- [x] Good UI design :white_check_mark: 
- [x] Application works as expected :white_check_mark:  
- [x] Implemented changes from the previous reviewer :white_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-23 09:10 UTC, merged

2023-06-23 09:41 UTC, AdnanOlarmmi commented on src/CSS/Book.module.css
> +  font-family: RobotoSlab, sans-serif;
You're welcome @ankitt26 🤗 

That is why we are here for you